import { UserSettings } from '../types';

export const DEFAULT_USER_SETTINGS: UserSettings = {
  notificationsEnabled: true,
  soundEnabled: true,
  hapticFeedback: true,
  riskPercent: 1.5,
  fixedLotSize: 0.1,
  dailyGoalValue: 200,
  dailyGoalType: 'fixed',
  dailyStopLoss: 100,
  dailyStopLossType: 'fixed',
  language: 'pt_BR',
  timezone: 'America/Sao_Paulo',
  userBanca: 10000,
  autoAnalyzeOnAssetChange: false,
  showEconomicNews: true,
  marketSessionAlerts: true,
  defaultLotMultiplier: 1.0,
  autoTradeEnabled: false,
  displayCurrency: 'USD',
  signalTimingMode: 'INSTANT',
  autoAIScanEnabled: false,
  aiSensitivity: 90,
  continueAfterDailyGoal: true,
  weeklyGoalValue: 800,
  monthlyGoalValue: 3000,
  tradingStyle: 'conservative',
  animationsEnabled: true,
  cacheEnabled: true,
  autoAIScanIntervalMs: 25000,
};
